repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: debug-statements
      - id: check-added-large-files
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
        - id: pyupgrade
          args:
              - '--py36-plus'
              - '--py3-plus'

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
        - id: isort # see .isort.cfg
          types: [file, python]

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - --line-length=120
          # Skip setting all quotes to double quote
          - '--skip-string-normalization'
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.3
    hooks:
    - id: flake8
      args:
        - --max-line-length=120
