services:
  powertofly:
    build: .
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:14.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    env_file:
      - .redis.env
    ports:
      - '6379:6379'
volumes:
  postgres_data:
